### ISSUE TITLE
Erreur SQl dans manage.php

### ISSUE THREAD

**Issue by JJDai54** [XoopsModulesArchive/myiframe#7]
There is too much quotes in the sql
--------------------------------------------------------------
line 131 replace

`$format = 'INSERT INTO "%s" (frame_created, frame_uid, frame_description, frame_width, frame_height, frame_align, frame_frameborder, frame_marginwidth, frame_marginheight, frame_scrolling, frame_hits, frame_url) VALUES (%u, %u, %s, %s, %s, %d, %d, %d, %d, %d, %u, %s)';`

by

`$format = 'INSERT INTO %s (frame_created, frame_uid, frame_description, frame_width, frame_height, frame_align, frame_frameborder, frame_marginwidth, frame_marginheight, frame_scrolling, frame_hits, frame_url) VALUES (%u, %u, %s, %s, %s, %d, %d, %d, %d, %d, %u, %s)';`

------------------------------------------------------------
line 151 replace
`            $format = 'UPDATE "%s" SET frame_description="%s", frame_width="%s", frame_height="%s", frame_align="%d", frame_frameborder="%d", frame_marginwidth="%d", frame_marginheight="%d", frame_scrolling="%d", frame_hits="%u", frame_url="%s" WHERE frame_frameid="%u"';`

by

`            $format = 'UPDATE %s SET frame_description=%s, frame_width=%s, frame_height=%s, frame_align="%d", frame_frameborder="%d", frame_marginwidth="%d", frame_marginheight="%d", frame_scrolling="%d", frame_hits="%u", frame_url=%s WHERE frame_frameid=%u';`

------------------------------------------------------------
line 194 replace
`$sql = sprintf('DELETE FROM "%s" WHERE frame_frameid = "%u"', $this->db->prefix('myiframe'), $object->getVar('frame_frameid'));`

by

`$sql = sprintf('DELETE FROM %s WHERE frame_frameid = "%u"', $this->db->prefix('myiframe'), $object->getVar('frame_frameid'));`

------------------------------------------------------------
line 281 replace
`        $sql = sprintf('UPDATE "%s" SET frame_hits = frame_hits+1 WHERE frame_frameid="%u"', $this->db->prefix('myiframe'), (int)$frame_id);`

by

`        $sql = sprintf('UPDATE %s SET frame_hits = frame_hits+1 WHERE frame_frameid="%u"', $this->db->prefix('myiframe'), (int)$frame_id);`

--------------------------------------------------
sorry for my english

**Comment by mambax7** [comment]
Could you submit a PR for it? 

Thanks!

**Comment by mambax7** [comment]
Actually, I've added your changes to what I was working on - you can check out the latest version here:
https://github.com/mambax7/myiframe/releases/tag/1.67.0_Beta.1

Thanks for the submission, and please keep testing and improving it, and letting us know about any issues!

**Comment by JJDai54** [comment]
What is a PR ?

**Comment by mambax7** [comment]
Pull Request
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests
